---
data_path: ../data
purchases_path: ../purchases
purchases_filename: purchases.csv
async_chunk_size: 3
count_epochs_to_write_on_disk: 10
output_format_str: async_info_{}.csv
time_sleep: 0.1
print: True
chunk_num: 1
chunk_size: 10000
purchase_table_name: public.purchases